services:
  - type: web
    name: suhba-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: DB_DATASOURCE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_ALLOWED_ORIGIN
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: prod
